#!/bin/bash

cd /usr/local/bin
# create aliases for everything but cyhy-mongo
GLOBIGNORE="cyhy-mongo"
for f in cyhy-*
do
  echo alias $f=\"docker run -ti --rm --name cyhy-core --volume \\\"\\\${CYHY_CONF_DIR:-/etc/cyhy}\\\":/etc/cyhy --volume \\\`pwd\\\`:/home/cyhy \\\"\\\${CYHY_CORE_IMAGE:-ncats/cyhy-core}\\\" $f\"
done
unset GLOBIGNORE

# create a function for cyhy-mongo
echo 'cyhy-mongo() { source <(docker run --volume "${CYHY_CONF_DIR:-/etc/cyhy}":/etc/cyhy ${CYHY_CORE_IMAGE:-ncats/cyhy-core} cyhy-mongo -p "$@") ; }'
