#!/bin/bash

echo '################################################################################'
echo '# The following output is used to setup aliases to containerized cyhy commands'
echo '# To apply these changes under bash use a command similar to:'
echo '# eval "$(docker run ncats/cyhy-core)"'
echo '#'
echo '# Environment variables:'
echo '# CYHY_CONF_DIR, defaults to "/etc/cyhy" if not set'
echo '# CYHY_CORE_IMAGE, defaults to "ncats/cyhy-core" if not set'
echo '################################################################################'
echo

cd /usr/local/bin

# create aliases for everything but cyhy-mongo
GLOBIGNORE="cyhy-mongo"

for f in cyhy-*
do
  echo alias $f=\"docker run -ti --rm --name cyhy-core --volume \\\"\\\${CYHY_CONF_DIR:-/etc/cyhy}\\\":/etc/cyhy --volume \\\`pwd\\\`:/home/cyhy \\\"\\\${CYHY_CORE_IMAGE:-ncats/cyhy-core}\\\" $f\"
done
unset GLOBIGNORE

# create a function for cyhy-mongo
echo 'cyhy-mongo() { source <(docker run --volume "${CYHY_CONF_DIR:-/etc/cyhy}":/etc/cyhy ${CYHY_CORE_IMAGE:-ncats/cyhy-core} cyhy-mongo -p "$@") ; }'
