---
name: Sort imports

on:  # yamllint disable-line rule:truthy
  # We use the default activity types for the pull_request event as specified here:
  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull_request
  pull_request:
    paths:
      # Ensure the workflow is run if it has been changed.
      - .github/workflows/sort-imports.yml
      - .isort.cfg
      - "**/*.py"
      - bin/**

# Set a default shell for any run steps. The `-Eueo pipefail` sets errtrace,
# nounset, errexit, and pipefail. The `-x` will print all commands as they are
# run. Please see the GitHub Actions documentation for more information:
# https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs
defaults:
  run:
    shell: bash -Eueo pipefail -x {0}

env:
  PIP_CACHE_DIR: ~/.cache/pip

jobs:
  diagnostics:
    name: Run diagnostics
    # This job does not need any permissions
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      # Note that a duplicate of this step must be added at the top of
      # each job.
      - name: Apply standard cisagov job preamble
        uses: cisagov/action-job-preamble@v1
        with:
          check_github_status: "true"
          # This functionality is poorly implemented and has been
          # causing problems due to the MITM implementation hogging or
          # leaking memory.  As a result we disable it by default.  If
          # you want to temporarily enable it, simply set
          # monitor_permissions equal to "true".
          #
          # TODO: Re-enable this functionality when practical.  See
          # cisagov/skeleton-generic#207 for more details.
          monitor_permissions: "false"
          output_workflow_context: "true"
          # Use a variable to specify the permissions monitoring
          # configuration. By default this will yield the
          # configuration stored in the cisagov organization-level
          # variable, but if you want to use a different configuration
          # then simply:
          # 1. Create a repository-level variable with the name
          # ACTIONS_PERMISSIONS_CONFIG.
          # 2. Set this new variable's value to the configuration you
          # want to use for this repository.
          #
          # Note in particular that changing the permissions
          # monitoring configuration *does not* require you to modify
          # this workflow.
          permissions_monitoring_config: ${{ vars.ACTIONS_PERMISSIONS_CONFIG }}
  sort-imports:
    # Only run if the pull request is from the original repository and not a forked
    # repository.
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: Sort Python imports with `isort`
    needs:
      - diagnostics
    permissions:
      # stefanzweifel/git-auto-commit-action needs this to commit changes
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Apply standard cisagov job preamble
        uses: cisagov/action-job-preamble@v1
        with:
          # This functionality is poorly implemented and has been
          # causing problems due to the MITM implementation hogging or
          # leaking memory.  As a result we disable it by default.  If
          # you want to temporarily enable it, simply set
          # monitor_permissions equal to "true".
          #
          # TODO: Re-enable this functionality when practical.  See
          # cisagov/skeleton-generic#207 for more details.
          monitor_permissions: "false"
          # Use a variable to specify the permissions monitoring
          # configuration. By default this will yield the
          # configuration stored in the cisagov organization-level
          # variable, but if you want to use a different configuration
          # then simply:
          # 1. Create a repository-level variable with the name
          # ACTIONS_PERMISSIONS_CONFIG.
          # 2. Set this new variable's value to the configuration you
          # want to use for this repository.
          #
          # Note in particular that changing the permissions
          # monitoring configuration *does not* require you to modify
          # this workflow.
          permissions_monitoring_config: ${{ vars.ACTIONS_PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v6
        with:
          # Needed by stefanzweifel/git-auto-commit-action to support the pull_request
          # trigger.
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GHA_AUTO_COMMIT_TOKEN || github.token }}
      - id: setup-env
        uses: cisagov/setup-env-github-action@v1
      - id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ steps.setup-env.outputs.python-version }}
      - uses: actions/cache@v5
        env:
          BASE_CACHE_KEY: >-
            ${{ github.job }}-${{ runner.os
            }}-py${{ steps.setup-python.outputs.python-version
            }}-
        with:
          # We do not use '**/setup.py' in the cache key so only the 'setup.py'
          # file in the root of the repository is used. This is in case a Python
          # package were to have a 'setup.py' as part of its internal codebase.
          key: >-
            ${{ env.BASE_CACHE_KEY }}${{
            hashFiles('setup.py') }}
          path: |
            ${{ env.PIP_CACHE_DIR }}
          restore-keys: |
            ${{ env.BASE_CACHE_KEY }}
      - name: Install isort
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install --upgrade isort==8.0.1
      # isort will automatically discover the .isort.cfg file
      - name: Sort imports with isort
        run: isort .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Sort Python imports with `isort`
